In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("Titanic.csv")

In [23]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.drop(["PassengerId","Name","Name"], axis=1 ,inplace=True)

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
DROP_COLUMNS= ["PassengerId","Name","Ticket"]

In [49]:
from config import DROP_COLUMNS
def drop_cols(df: pd.DataFrame, cols : list[str])-> pd.DataFrame:
    '''Drop specific cols from df  '''
    return df.drop(columns = cols)

Drop Cols

In [26]:
df = drop_cols(df,DROP_COLUMNS)

In [27]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

Check Data Type

In [31]:
class Student:
    def __init__(self,name)->None :
        self._name = name 
    @property
    def name(self):
        return self._name

In [32]:
s1 = Student('Shahd')
s1.name

'Shahd'

In [33]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [ ]:
dtypes = df.dtypes
n_uniq = df.nunique()
# n_uniq
pd.DataFrame({"Dtypes: ": dtypes,"Num_uniqe:" : n_uniq})

         Dtypes:   Num_uniqe:
Survived    int64           2
Pclass      int64           3
Sex           str           2
Age       float64          88
SibSp       int64           7
Parch       int64           7
Fare      float64         248
Cabin         str         147
Embarked      str           3

In [38]:
pd.DataFrame({"Dtypes: ": dtypes,"Num_uniqe:" : n_uniq}).T

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes:       int64  int64  str  float64  int64  int64  float64   str      str
Num_uniqe:        2      3    2       88      7      7      248   147        3

In [41]:
def summary(df:pd.DataFrame)-> pd.DataFrame:
    dtypes = df.dtypes
    n_uniq = df.nunique()
    return  pd.DataFrame({"Dtypes: ": dtypes,"Num_uniqe:" : n_uniq}).T

In [42]:
summary(df)

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes:       int64  int64  str  float64  int64  int64  float64   str      str
Num_uniqe:        2      3    2       88      7      7      248   147        3

In [45]:
from ps import summary
summary(df)

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes:       int64  int64  str  float64  int64  int64  float64   str      str
Num_uniqe:        2      3    2       88      7      7      248   147        3

In [53]:
cols = ['Pclass','Survived','SibSp','Sex','Embarked','Parch']
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [72]:
null = df.isnull().sum() # بيعد الTrue وهنا ال true الخليه الفاضيه 
null

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [73]:
df.shape[0]

889

In [74]:
ratio = null/df.shape[0]
pd.DataFrame({"nulls_sum:" : null ,"Ratio: " : ratio}).T

            Survived  Pclass  Sex       Age  SibSp  Parch  Fare  Embarked
nulls_sum:       0.0     0.0  0.0  177.0000    0.0    0.0   0.0       0.0
Ratio:           0.0     0.0  0.0    0.1991    0.0    0.0   0.0       0.0

In [75]:
df = df.dropna(subset=['Embarked'])

In [76]:
df = df.drop('Cabin',axis=1)

KeyError: "['Cabin'] not found in axis"

In [84]:
mean = df['Age'].mean()
print(mean)

print('#' * 50)
median = df['Age'].median()

print(median)

df['Age'] = df['Age'].fillna(median)

29.64209269662921
##################################################
28.0

In [85]:
null = df.isnull().sum() 
ratio = null/df.shape[0]
pd.DataFrame({"nulls_sum:" : null ,"Ratio: " : ratio}).T

            Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
nulls_sum:       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
Ratio:           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [87]:
#num_cols = df.select_dtypes('number').columns
num_cols = ['Age', 'Fare']