In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s = pd.Series([1,2,3,4],index = ['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
data = [[1,444,'abc'],
[2,555,'def'],
[3,666,'ghi'],
[4,444,'xyz']]
df = pd.DataFrame(data,columns = ["Idx","std_id","depart"])
df

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [7]:
data = {"Idx":[1,2,3,4],
"std_id":[444,555,666,777],
"depart":['abc','def','xyz','ghi']}
df = pd.DataFrame(data)
df

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    xyz
3    4     777    ghi

In [12]:
display(df)
colums = ['idx-1','std_id1','dep']
index = ['a','b','c','d']
df.columns = colums
df.index = index
display(df)

   idx-1  std_id1  dep
0      1      444  abc
1      2      555  def
2      3      666  xyz
3      4      777  ghi

   idx-1  std_id1  dep
a      1      444  abc
b      2      555  def
c      3      666  xyz
d      4      777  ghi

In [15]:
#df.dtypes
df['idx-1'].dtype

dtype('int64')

In [18]:
df['std_id1'] = df['std_id1'].astype('category')
df.dtypes

idx-1         int64
std_id1    category
dep             str
dtype: object

In [24]:
cols = ['idx-1', 'dep']
df[cols] = df[cols].astype('category')
df.dtypes

KeyError: "None of [Index(['idx-1', 'dep'], dtype='str')] are in the [columns]"

In [ ]:
data = {"Idx":[1,2,3,4],
"std_id":[444,555,666,777],
"depart":['abc','def','xyz','ghi']}
df = pd.DataFrame(data)
df

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    xyz
3    4     777    ghi

In [22]:
df.head()

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    xyz
3    4     777    ghi

In [23]:
df.tail(1)

   Idx  std_id depart
3    4     777    ghi

In [25]:
df.describe()

            Idx      std_id
count  4.000000    4.000000
mean   2.500000  610.500000
std    1.290994  143.300384
min    1.000000  444.000000
25%    1.750000  527.250000
50%    2.500000  610.500000
75%    3.250000  693.750000
max    4.000000  777.000000

In [27]:
df.columns

Index(['Idx', 'std_id', 'depart'], dtype='str')

In [29]:
df['std_id'].unique()
df['std_id'].nunique()

4

In [31]:
df['std_id'].max()
df['std_id'].idxmax()

3

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Idx     4 non-null      int64
 1   std_id  4 non-null      int64
 2   depart  4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [33]:
d = df['depart'].value_counts()
d

depart
abc    1
def    1
xyz    1
ghi    1
Name: count, dtype: int64

In [34]:
df['std_id'].sum()

np.int64(2442)

In [35]:
df['depart'].values

<StringArray>
['abc', 'def', 'xyz', 'ghi']
Length: 4, dtype: str

In [36]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'xyz'],
       [4, 777, 'ghi']], dtype=object)

In [38]:
x = df.values
type(x)

numpy.ndarray

In [40]:
df1 = df.replace(555,"shahd",inplace =True)
df

   Idx std_id depart
0    1    444    abc
1    2  shahd    def
2    3    666    xyz
3    4    777    ghi

In [42]:
df.std_id = df.std_id.map({444:"ytrff",888:"dddd"})
df

   Idx std_id depart
0    1  ytrff    NaN
1    2    NaN    NaN
2    3    NaN    NaN
3    4    NaN    NaN

In [43]:
df.depart.iloc[2]

nan

In [44]:
data = {"Idx":[1,2,3,4],
"std_id":[444,555,666,777],
"depart":['abc','def','xyz','ghi']}
df = pd.DataFrame(data)
df

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    xyz
3    4     777    ghi

In [49]:
x = df.iloc[:, 0:2]
y = df.iloc[:, -1]